name: Make Canary Release

on:
  push:
    branches:
      - 'updater'
    paths:
      - '.github/makeNewCanary'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Grab Source
      
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant permission shell scripts
      run: chmod +x .github/*.sh
      
    - name: Update Versions
      run: .github/bumpVersion.sh ${{ github.run_id }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "32.0.0"
          
    - name: Run the zip script
      run: .github/make_zip.sh
        
    - name: Upload Zip
      uses: actions/upload-artifact@v2
      with: 
        name: AOSPMods.zip
        path: output
 
    - name: Commit version bump
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'updater'
        commit-message: 'Version update: Release'
        force-add: 'true'
        files: MagiskMod/module.prop app/build.gradle latestVersion.json
        name: GitHub
        email: aospmods@siava.sh
