name: Make Canary Release

on:
  push:
    branches:
      - 'canary'
    paths:
      - '.github/edit2MakeNewCanary'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch: 
       # Inputs the workflow accepts.
       inputs:
         name:
           # Friendly description to be shown in the UI instead of 'name'
           description: 'Make Canary Release'
           # Input has to be provided for the workflow to run
           required: true 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Grab Source
      run: git clone --recurse-submodules https://github.com/TOBY19k/QSMods .
      
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant permission shell scripts
      run: chmod +x .github/*.sh

    - name: Generate Changelog
      run: .github/extractChanges.sh

    - name: Update Versions
      run: .github/bumpVersion.sh ${{ github.run_id }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Run the zip script
      run: .github/make_zip.sh

    - name: Prepare upload artifact
      run: |
        rm -rf tmp
        mkdir -p tmp/xposed tmp/full
        unzip -o output/xposed/*.zip -d tmp/xposed
        unzip -o output/full/*.zip -d tmp/full
        
    - name: Upload Xposed Zip
      uses: actions/upload-artifact@v2
      with: 
        name: AOSPMods_Xposed.zip
        path: tmp/xposed

    - name: Upload Full Zip
      uses: actions/upload-artifact@v2
      with:
        name: AOSPMods_Full.zip
        path: tmp/full
